version: '3.1'

services:
  db:
    image: mysql:latest
    container_name: my-mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: cantor_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_cantor_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: my-phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: example
      PMA_ARBITRARY: 1
    ports:
      - "8080:80"
    depends_on:
      - db

  web:
    build:
      dockerfile: ./Dockerfile
    container_name: my-php
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: example
      DB_NAME: cantordb
    volumes:
      - .:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - db

volumes:
  mysql_cantor_data:
  